# Generated by Django 2.0.6 on 2021-01-11 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=128)),
                ('age', models.CharField(max_length=20)),
                ('sex', models.CharField(max_length=28)),
                ('bir', models.DateField(auto_now=True, null=True)),
                ('phone', models.CharField(max_length=28)),
            ],
            options={
                'verbose_name': '学生表',
                'verbose_name_plural': '学生表',
                'db_table': 'bz_stu',
            },
        ),
    ]
